import { CalendarRange, Eye, EyeOff, Landmark, MapPin, UserRound } from 'lucide-react'
import { useState } from 'react'
import type { PartnershipTrackerSummary } from '../../../../../../packages/types/src/partnership-tracker'
import { PerformanceMetricStrip } from './PerformanceMetricStrip'
import { formatEinInput } from '../einInput'

const currency = (value?: string | null) => value == null ? 'Not entered' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(Number(value))
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(`${value}T00:00:00Z`)) : '—'

export function PartnershipOverview({ summary }: { summary: PartnershipTrackerSummary }) {
  const partnership = summary.partnership
  const [showEin, setShowEin] = useState(false)
  const formattedEin = partnership.ein ? formatEinInput(partnership.ein) : null
  const address = [partnership.addressLine1, partnership.addressLine2, [partnership.addressCity, partnership.addressRegion].filter(Boolean).join(', '), partnership.addressPostalCode, partnership.addressCountry].filter(Boolean).join(' · ')
  const cards = [
    { label: 'Committed capital', value: currency(summary.currentCommittedCapital?.amount), detail: summary.currentCommittedCapital ? `Effective ${date(summary.currentCommittedCapital.date)}` : 'Add an effective-dated total', icon: Landmark },
    { label: 'K-1 history', value: summary.earliestK1Year == null ? 'No years' : summary.earliestK1Year === summary.latestTaxYear ? String(summary.latestTaxYear) : `${summary.earliestK1Year}–${summary.latestTaxYear}`, detail: summary.latestWorkflowStatus?.replaceAll('_', ' ') ?? 'Start any tax year', icon: CalendarRange },
  ]
  return <div className="space-y-5">
    <PerformanceMetricStrip summary={summary} />
    <section aria-labelledby="partnership-profile-title" className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Fund identity</p><h3 id="partnership-profile-title" className="mt-1 font-serif text-lg font-semibold text-gray-950">Partnership profile</h3></div></div><dl className="mt-4 grid gap-x-6 gap-y-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs uppercase tracking-wide text-gray-500">EIN</dt><dd className="mt-1 flex min-h-10 items-center gap-2 font-mono font-semibold text-gray-900"><span>{formattedEin ? (showEin ? formattedEin : '**-*******') : 'Not entered'}</span>{formattedEin && <button type="button" aria-label={showEin ? 'Mask EIN' : 'Unmask EIN'} aria-pressed={showEin} onClick={() => setShowEin((shown) => !shown)} className="grid min-h-10 min-w-10 place-items-center rounded-md text-gray-400 hover:bg-gray-100 hover:text-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus">{showEin ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button>}</dd></div><div><dt className="flex items-center gap-1.5 text-xs uppercase tracking-wide text-gray-500"><UserRound className="h-3.5 w-3.5" />Fund manager</dt><dd className="mt-2 font-semibold text-gray-900">{partnership.fundManager ?? 'Not entered'}</dd></div><div><dt className="text-xs uppercase tracking-wide text-gray-500">Inception date</dt><dd className="mt-2 font-semibold text-gray-900">{date(partnership.inceptionDate)}</dd></div><div className="sm:col-span-2 lg:col-span-1"><dt className="flex items-center gap-1.5 text-xs uppercase tracking-wide text-gray-500"><MapPin className="h-3.5 w-3.5" />Address</dt><dd className="mt-2 text-sm font-medium leading-5 text-gray-900">{address || 'Not entered'}</dd></div></dl></section>
    <div className="grid gap-4 md:grid-cols-2">{cards.map((card) => <section key={card.label} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-medium text-gray-500"><card.icon className="h-4 w-4" />{card.label}</div><p className="mt-3 text-2xl font-semibold text-gray-950">{card.value}</p><p className="mt-1 text-xs text-gray-500">{card.detail}</p></section>)}</div>
    <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-gray-950">Latest tax position</h3><dl className="mt-4 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs uppercase tracking-wide text-gray-500">Ending outside basis</dt><dd className="mt-1 text-lg font-semibold text-gray-900">{currency(summary.latestEndingOutsideBasis)}</dd></div><div><dt className="text-xs uppercase tracking-wide text-gray-500">Latest tax year</dt><dd className="mt-1 text-lg font-semibold text-gray-900">{summary.latestTaxYear ?? '—'}</dd></div><div><dt className="text-xs uppercase tracking-wide text-gray-500">Warnings</dt><dd className="mt-1 text-lg font-semibold text-gray-900">{summary.warningCount}</dd></div></dl></section>
  </div>
}
