output "document_bucket_name" { value = aws_s3_bucket.documents.id }
output "document_bucket_arn" { value = aws_s3_bucket.documents.arn }
output "kms_key_arn" { value = aws_kms_key.documents.arn }
output "start_queue_url" { value = aws_sqs_queue.start.url }
output "start_queue_arn" { value = aws_sqs_queue.start.arn }
output "completion_queue_url" { value = aws_sqs_queue.completion.url }
output "completion_queue_arn" { value = aws_sqs_queue.completion.arn }
output "start_dlq_arn" { value = aws_sqs_queue.start_dlq.arn }
output "completion_dlq_arn" { value = aws_sqs_queue.completion_dlq.arn }
output "worker_service_name" { value = aws_ecs_service.worker.name }
output "worker_log_group_name" { value = aws_cloudwatch_log_group.worker.name }
output "reconciler_rule_name" { value = aws_cloudwatch_event_rule.reconciler.name }
output "bda_blueprint_arn" { value = try(awscc_bedrock_blueprint.k1[0].blueprint_arn, null) }
output "bda_fallback_blueprint_arn" { value = try(awscc_bedrock_blueprint.fallback[0].blueprint_arn, null) }
output "bda_project_arn" { value = try(awscc_bedrock_data_automation_project.k1[0].project_arn, null) }
output "bda_project_stage" { value = try(awscc_bedrock_data_automation_project.k1[0].project_stage, null) }
output "bda_blueprint_stage" { value = try(awscc_bedrock_blueprint.k1[0].blueprint_stage, null) }
