import React from 'react'
import { SectionCard } from './SectionCard'
import { BarChart2Icon } from 'lucide-react'
import { DataTable, type Column } from '../../../components/DataTable'
import type { ActivityDetailRow } from 'packages/types/src'

interface ActivityDetailPreviewProps {
  rows: ActivityDetailRow[]
  loading?: boolean
}

const COLUMNS: Column<ActivityDetailRow>[] = [
  {
    key: 'taxYear',
    header: 'Tax Year',
    sortable: true,
    render: (row) => <span className="font-medium tabular-nums">{row.taxYear}</span>,
  },
  {
    key: 'sources',
    header: 'Trigger Sources',
    render: (row) => {
      const chips = [
        row.sourceSignals.hasK1 ? 'K-1' : null,
        row.sourceSignals.hasCapitalActivity ? 'Capital Activity' : null,
        row.sourceSignals.hasFmv ? 'FMV' : null,
        row.sourceSignals.hasManualInput ? 'Manual Input' : null,
      ].filter((item): item is string => Boolean(item))

      return chips.length ? (
        <div className="flex flex-wrap gap-1">
          {chips.map((chip) => (
            <span
              key={chip}
              className="inline-flex items-center rounded-full border border-gray-200 px-2 py-0.5 text-xs text-text-secondary"
            >
              {chip}
            </span>
          ))}
        </div>
      ) : (
        <span className="text-text-tertiary">—</span>
      )
    },
  },
  {
    key: 'reportedDistributionUsd',
    header: 'Reported Dist.',
    align: 'right',
    render: (row) =>
      row.reportedDistributionUsd != null ? (
        <span className="tabular-nums">${row.reportedDistributionUsd.toLocaleString()}</span>
      ) : (
        <span className="text-text-tertiary">—</span>
      ),
  },
  {
    key: 'paidInUsd',
    header: 'Paid-In',
    align: 'right',
    render: (row) =>
      row.paidInUsd != null ? (
        <span className="tabular-nums">${row.paidInUsd.toLocaleString()}</span>
      ) : (
        <span className="text-text-tertiary">—</span>
      ),
  },
  {
    key: 'tvpi',
    header: 'TVPI',
    align: 'right',
    render: (row) =>
      row.tvpi != null ? (
        <span className="tabular-nums">{row.tvpi.toFixed(2)}x</span>
      ) : (
        <span className="text-text-tertiary">—</span>
      ),
  },
]

export function ActivityDetailPreview({ rows, loading = false }: ActivityDetailPreviewProps) {
  return (
    <SectionCard title="Activity Detail" subtitle="Rows update from K-1, capital activity, FMV, and manual reporting inputs">
      <DataTable
        columns={COLUMNS}
        data={rows}
        state={loading ? 'loading' : rows.length ? 'populated' : 'empty'}
        emptyTitle="No activity detail rows"
        emptyDescription="Rows appear automatically as K-1s are finalized and as capital or FMV data is recorded."
      />
      {rows.length === 0 && (
        <div className="px-5 py-4 border-t border-border text-xs text-text-tertiary inline-flex items-center gap-1">
          <BarChart2Icon className="w-3.5 h-3.5" />
          Annual rows are generated by source triggers; no manual row creation is required.
        </div>
      )}
    </SectionCard>
  )
}
