export type K1FieldSection = 'entityMapping' | 'partnershipMapping' | 'core'

export type K1AzureValueKind =
  | 'string'
  | 'number'
  | 'currency'
  | 'percentage'
  | 'date'
  | 'boolean'

export interface AzureFieldMapEntry {
  /** Canonical snake_case identifier; unique across the map. */
  canonicalName: string
  /** Human-facing label rendered in the review workspace. */
  label: string
  /** Which review section the field lives in. */
  section: K1FieldSection
  /** Whether the field must be present and non-null before approval. */
  required: boolean
  /** Dotted path into AnalyzeResult.documents[0].fields (using valueObject nesting). */
  azurePath: string
  /** How to project the Azure DocumentField into the stored string. */
  valueKind: K1AzureValueKind
}

export const azureFieldMap: readonly AzureFieldMapEntry[] = [
  // --- Partnership info ---
  {
    canonicalName: 'partnership_ein',
    label: 'Partnership EIN',
    section: 'partnershipMapping',
    required: true,
    azurePath: 'Partnership.Identifier.Tin',
    valueKind: 'string',
  },
  {
    canonicalName: 'partnership_name',
    label: 'Partnership Name',
    section: 'partnershipMapping',
    required: true,
    azurePath: 'Partnership.Name',
    valueKind: 'string',
  },
  {
    canonicalName: 'partnership_address',
    label: 'Partnership Address',
    section: 'partnershipMapping',
    required: false,
    azurePath: 'Partnership.Address',
    valueKind: 'string',
  },
  {
    canonicalName: 'irs_center',
    label: 'IRS Processing Center',
    section: 'partnershipMapping',
    required: false,
    azurePath: 'Partnership.IRSCenter',
    valueKind: 'string',
  },
  {
    canonicalName: 'is_publicly_traded',
    label: 'Publicly Traded Partnership',
    section: 'partnershipMapping',
    required: false,
    azurePath: 'Partnership.IsPubliclyTradedPartnership',
    valueKind: 'boolean',
  },
  // --- Partner (entity) info ---
  {
    canonicalName: 'partner_tin',
    label: 'Partner TIN',
    section: 'entityMapping',
    required: true,
    azurePath: 'Partner.Identifier.Tin',
    valueKind: 'string',
  },
  {
    canonicalName: 'partner_name',
    label: 'Partner Name',
    section: 'entityMapping',
    required: true,
    azurePath: 'Partner.Name',
    valueKind: 'string',
  },
  {
    canonicalName: 'partner_address',
    label: 'Partner Address',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Address',
    valueKind: 'string',
  },
  {
    canonicalName: 'partner_entity_type',
    label: 'Partner Entity Type',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.EntityType',
    valueKind: 'string',
  },
  {
    canonicalName: 'is_general_partner',
    label: 'General Partner / LLC Manager',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.IsGeneralPartnerOrLLCMemberManager',
    valueKind: 'boolean',
  },
  {
    canonicalName: 'is_domestic_partner',
    label: 'Domestic Partner',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.IsDomesticPartner',
    valueKind: 'boolean',
  },
  // --- Profit / Loss / Capital percentages ---
  {
    canonicalName: 'profit_share_beginning',
    label: 'Profit Share % (Beginning)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Profit.Beginning',
    valueKind: 'percentage',
  },
  {
    canonicalName: 'profit_share_ending',
    label: 'Profit Share % (Ending)',
    section: 'entityMapping',
    required: true,
    azurePath: 'Partner.Profit.Ending',
    valueKind: 'percentage',
  },
  {
    canonicalName: 'loss_share_beginning',
    label: 'Loss Share % (Beginning)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Loss.Beginning',
    valueKind: 'percentage',
  },
  {
    canonicalName: 'loss_share_ending',
    label: 'Loss Share % (Ending)',
    section: 'entityMapping',
    required: true,
    azurePath: 'Partner.Loss.Ending',
    valueKind: 'percentage',
  },
  {
    canonicalName: 'capital_share_beginning',
    label: 'Capital Share % (Beginning)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Capital.Beginning',
    valueKind: 'percentage',
  },
  {
    canonicalName: 'capital_share_ending',
    label: 'Capital Share % (Ending)',
    section: 'entityMapping',
    required: true,
    azurePath: 'Partner.Capital.Ending',
    valueKind: 'percentage',
  },
  // --- Liabilities ---
  {
    canonicalName: 'liab_nonrecourse_beginning',
    label: 'Nonrecourse Liabilities (Beginning)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Liabilities.Nonrecourse.Beginning',
    valueKind: 'currency',
  },
  {
    canonicalName: 'liab_nonrecourse_ending',
    label: 'Nonrecourse Liabilities (Ending)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Liabilities.Nonrecourse.Ending',
    valueKind: 'currency',
  },
  {
    canonicalName: 'liab_qualified_nonrecourse_beginning',
    label: 'Qualified Nonrecourse Liabilities (Beginning)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Liabilities.QualifiedNonrecourse.Beginning',
    valueKind: 'currency',
  },
  {
    canonicalName: 'liab_qualified_nonrecourse_ending',
    label: 'Qualified Nonrecourse Liabilities (Ending)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Liabilities.QualifiedNonrecourse.Ending',
    valueKind: 'currency',
  },
  {
    canonicalName: 'liab_recourse_beginning',
    label: 'Recourse Liabilities (Beginning)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Liabilities.Recourse.Beginning',
    valueKind: 'currency',
  },
  {
    canonicalName: 'liab_recourse_ending',
    label: 'Recourse Liabilities (Ending)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.Liabilities.Recourse.Ending',
    valueKind: 'currency',
  },
  // --- Capital account ---
  {
    canonicalName: 'capital_beginning',
    label: 'Capital Account: Beginning Balance',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.CapitalAccount.BeginningCapital',
    valueKind: 'currency',
  },
  {
    canonicalName: 'capital_contributed',
    label: 'Capital Account: Contributions',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.CapitalAccount.CapitalContributed',
    valueKind: 'currency',
  },
  {
    canonicalName: 'capital_current_year_net_income',
    label: 'Capital Account: Current Year Net Income',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.CapitalAccount.CurrentYearNetIncome',
    valueKind: 'currency',
  },
  {
    canonicalName: 'capital_other_increase_decrease',
    label: 'Capital Account: Other Increase (Decrease)',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.CapitalAccount.OtherIncreaseOrDecrease',
    valueKind: 'currency',
  },
  {
    canonicalName: 'capital_withdrawals_distributions',
    label: 'Capital Account: Withdrawals & Distributions',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.CapitalAccount.WithdrawalsAndDistributions',
    valueKind: 'currency',
  },
  {
    canonicalName: 'capital_ending',
    label: 'Capital Account: Ending Balance',
    section: 'entityMapping',
    required: false,
    azurePath: 'Partner.CapitalAccount.EndingCapital',
    valueKind: 'currency',
  },
  // --- Part III: income / deductions / credits ---
  {
    canonicalName: 'box_1_ordinary_income',
    label: 'Box 1: Ordinary Business Income (Loss)',
    section: 'core',
    required: true,
    azurePath: 'PartIII.OrdinaryBusinessIncome',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_2_net_rental_real_estate',
    label: 'Box 2: Net Rental Real Estate Income (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.NetRentalRealEstateIncome',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_3_other_net_rental',
    label: 'Box 3: Other Net Rental Income (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.OtherNetRentalIncome',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_4a_guaranteed_payments_services',
    label: 'Box 4a: Guaranteed Payments for Services',
    section: 'core',
    required: false,
    azurePath: 'PartIII.GuaranteedPaymentsServices',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_4b_guaranteed_payments_capital',
    label: 'Box 4b: Guaranteed Payments for Capital',
    section: 'core',
    required: false,
    azurePath: 'PartIII.GuaranteedPaymentsCapital',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_4c_total_guaranteed_payments',
    label: 'Box 4c: Total Guaranteed Payments',
    section: 'core',
    required: false,
    azurePath: 'PartIII.TotalGuaranteedPayments',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_5_interest_income',
    label: 'Box 5: Interest Income',
    section: 'core',
    required: false,
    azurePath: 'PartIII.InterestIncome',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_6a_ordinary_dividends',
    label: 'Box 6a: Ordinary Dividends',
    section: 'core',
    required: false,
    azurePath: 'PartIII.OrdinaryDividends',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_6b_qualified_dividends',
    label: 'Box 6b: Qualified Dividends',
    section: 'core',
    required: false,
    azurePath: 'PartIII.QualifiedDividends',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_6c_dividend_equivalents',
    label: 'Box 6c: Dividend Equivalents',
    section: 'core',
    required: false,
    azurePath: 'PartIII.DividendEquivalents',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_7_royalties',
    label: 'Box 7: Royalties',
    section: 'core',
    required: false,
    azurePath: 'PartIII.Royalties',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_8_net_short_term_capital_gain',
    label: 'Box 8: Net Short-Term Capital Gain (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.NetShortTermCapitalGain',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_9a_net_long_term_capital_gain',
    label: 'Box 9a: Net Long-Term Capital Gain (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.NetLongTermCapitalGain',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_9b_collectibles_gain',
    label: 'Box 9b: Collectibles (28%) Gain (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.CollectiblesGain',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_9c_unrecaptured_1250_gain',
    label: 'Box 9c: Unrecaptured Section 1250 Gain',
    section: 'core',
    required: false,
    azurePath: 'PartIII.UnrecapturedSection1250Gain',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_10_net_section_1231_gain',
    label: 'Box 10: Net Section 1231 Gain (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.NetSection1231Gain',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_11_other_income',
    label: 'Box 11: Other Income (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.OtherIncome',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_12_section_179_deduction',
    label: 'Box 12: Section 179 Deduction',
    section: 'core',
    required: false,
    azurePath: 'PartIII.Section179Deduction',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_13_other_deductions',
    label: 'Box 13: Other Deductions',
    section: 'core',
    required: false,
    azurePath: 'PartIII.OtherDeductions',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_14_self_employment_earnings',
    label: 'Box 14: Self-Employment Earnings (Loss)',
    section: 'core',
    required: false,
    azurePath: 'PartIII.SelfEmploymentEarnings',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_15_credits',
    label: 'Box 15: Credits',
    section: 'core',
    required: false,
    azurePath: 'PartIII.Credits',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_16_schedule_k3_attached',
    label: 'Box 16: Schedule K-3 Attached',
    section: 'core',
    required: false,
    azurePath: 'PartIII.ScheduleK3Attached',
    valueKind: 'boolean',
  },
  {
    canonicalName: 'box_17_amt_items',
    label: 'Box 17: Alternative Minimum Tax (AMT) Items',
    section: 'core',
    required: false,
    azurePath: 'PartIII.AlternativeMinimumTaxItems',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_18_tax_exempt_income',
    label: 'Box 18: Tax-Exempt Income and Nondeductible Expenses',
    section: 'core',
    required: false,
    azurePath: 'PartIII.TaxExemptIncomeAndNondeductibleExpenses',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_19_distributions',
    label: 'Box 19: Distributions',
    section: 'core',
    required: true,
    azurePath: 'PartIII.Distributions',
    valueKind: 'currency',
  },
  {
    canonicalName: 'box_20_other_information',
    label: 'Box 20: Other Information',
    section: 'core',
    required: false,
    azurePath: 'PartIII.OtherInformation',
    valueKind: 'string',
  },
  {
    canonicalName: 'box_21_foreign_taxes',
    label: 'Box 21: Foreign Taxes Paid or Accrued',
    section: 'core',
    required: false,
    azurePath: 'PartIII.ForeignTaxesPaidOrAccrued',
    valueKind: 'currency',
  },
] as const
