/** Master code legend transcribed from the supplied 2019 Form 1065 Schedule K-1,
 * page 2. This is reference data, never evidence of an entered amount. Meanings
 * are revision-specific: do not apply the 2019 dictionary to another tax year.
 */
export const K1_CODE_REFERENCE_2019: Readonly<Record<number, readonly string[]>> = {
  11: ['Other portfolio income (loss)', 'Involuntary conversions', 'Sec. 1256 contracts & straddles', 'Mining exploration costs recapture', 'Cancellation of debt', 'Section 743(b) positive adjustments', 'Section 965(a) inclusion', 'Income under subpart F (other than inclusions under sections 951A and 965)', 'Other income (loss)'],
  13: ['Cash contributions (60%)', 'Cash contributions (30%)', 'Noncash contributions (50%)', 'Noncash contributions (30%)', 'Capital gain property to a 50% organization (30%)', 'Capital gain property (20%)', 'Contributions (100%)', 'Investment interest expense', 'Deductions-royalty income', 'Section 59(e)(2) expenditures', 'Excess business interest expense', 'Deductions-portfolio (other)', 'Amounts paid for medical insurance', 'Educational assistance benefits', 'Dependent care benefits', 'Preproductive period expenses', 'Commercial revitalization deduction from rental real estate activities', 'Pensions and IRAs', 'Reforestation expense deduction', 'Reserved for future use', 'Reserved for future use', 'Section 743(b) negative adjustments', 'Other deductions', 'Section 965(c) deduction'],
  14: ['Net earnings (loss) from self-employment', 'Gross farming or fishing income', 'Gross non-farm income'],
  15: ['Low-income housing credit (section 42(j)(5)) from pre-2008 buildings', 'Low-income housing credit (other) from pre-2008 buildings', 'Low-income housing credit (section 42(j)(5)) from post-2007 buildings', 'Low-income housing credit (other) from post-2007 buildings', 'Qualified rehabilitation expenditures (rental real estate)', 'Other rental real estate credits', 'Other rental credits', 'Undistributed capital gains credit', 'Biofuel producer credit', 'Work opportunity credit', 'Disabled access credit', 'Empowerment zone employment credit', 'Credit for increasing research activities', 'Credit for employer social security and Medicare taxes', 'Backup withholding', 'Other credits'],
  16: ['Name of country or U.S. possession', 'Gross income from all sources', 'Gross income sourced at partner level', 'Reserved for future use', 'Foreign gross income sourced at partnership level - Foreign branch category', 'Foreign gross income sourced at partnership level - Passive category', 'Foreign gross income sourced at partnership level - General category', 'Foreign gross income sourced at partnership level - Other', 'Deductions allocated and apportioned at partner level - Interest expense', 'Deductions allocated and apportioned at partner level - Other', 'Reserved for future use', 'Deductions allocated and apportioned at partnership level - Foreign branch category', 'Deductions allocated and apportioned at partnership level - Passive category', 'Deductions allocated and apportioned at partnership level - General category', 'Deductions allocated and apportioned at partnership level - Other', 'Total foreign taxes paid', 'Total foreign taxes accrued', 'Reduction in taxes available for credit', 'Foreign trading gross receipts', 'Extraterritorial income exclusion', 'Reserved for future use', 'Reserved for future use', 'Section 965 information', 'Other foreign transactions'],
  17: ['Post-1986 depreciation adjustment', 'Adjusted gain or loss', 'Depletion (other than oil & gas)', 'Oil, gas, & geothermal-gross income', 'Oil, gas, & geothermal-deductions', 'Other AMT items'],
  18: ['Tax-exempt interest income', 'Other tax-exempt income', 'Nondeductible expenses'],
  19: ['Cash and marketable securities', 'Distribution subject to section 737', 'Other property'],
  20: ['Investment income', 'Investment expenses', 'Fuel tax credit information', 'Qualified rehabilitation expenditures (other than rental real estate)', 'Basis of energy property', 'See partner instructions', 'See partner instructions', 'Recapture of investment credit', 'Recapture of other credits', 'Look-back interest-completed long-term contracts', 'Look-back interest-income forecast method', 'Dispositions of property with section 179 deductions', 'Recapture of section 179 deduction', 'Interest expense for corporate partners', ...Array<string>(11).fill('See partner instructions'), 'Section 199A information', 'Section 704(c) information', 'Section 751 gain (loss)', 'Section 1(h)(5) gain (loss)', 'Deemed section 1250 unrecaptured gain', 'Excess taxable income', 'Excess business interest income', 'Gross receipts for section 59A(e)', 'Other information'],
}

// The second supplied reference is the 2025 "Schedule K-1 (1065) Boxes and
// Codes" sheet. Arrays follow A..Z, AA..AZ, BA..; ZZ is stored separately.
export const K1_CODE_REFERENCE_2025: Readonly<Record<number, readonly string[]>> = {
  11: [...K1_CODE_REFERENCE_2019[11].slice(0, 6), 'Reserved for future use', 'Reserved for future use', 'Gain (loss) from disposition of oil, gas, geothermal, or other mineral properties (section 59(e))', 'Recoveries of tax benefit items', 'Gambling gains and losses', 'Any income, gain, or loss to the partnership from a distribution under section 751(b)', 'Gain eligible for section 1045 rollover (replacement stock purchased by partnership)', 'Gain eligible for section 1045 rollover (replacement stock not purchased by partnership)', 'Sale or exchange of QSB stock with section 1202 exclusion', 'Gain or loss on disposition of farm recapture property and other items to which section 1252 applies', 'Gain or loss on Fannie Mae or Freddie Mac qualified preferred stock', 'Specially allocated ordinary gain (loss)', 'Non-portfolio capital gain (loss)', ...Array<string>(5).fill('Reserved for future use')],
  13: [...K1_CODE_REFERENCE_2019[13].slice(0, 16), 'Reserved for future use', ...K1_CODE_REFERENCE_2019[13].slice(17, 22), 'Soil and water conservation', 'Qualified film, television, theatrical, and sound recording production expenses', 'Expenditures for removal of barriers', 'Itemized deductions', 'Contributions to a capital construction fund (CCF)', 'Penalty on early withdrawal of savings', 'Interest expense allocated to debt-financed distributions', 'Interest expense on working interest in oil or gas', 'Deductions - portfolio income', ...Array<string>(5).fill('Reserved for future use')],
  14: K1_CODE_REFERENCE_2019[14],
  15: ['Zero-emission nuclear power production credit', 'Production from advanced nuclear power facilities credit', ...K1_CODE_REFERENCE_2019[15].slice(2, 15), 'Unused investment credit from qualifying advanced coal project credit or qualifying gasification project credit from cooperatives', 'Unused investment credit from qualifying advanced energy project credit from cooperatives', 'Unused investment credit from qualifying advanced manufacturing investment credit from cooperatives', 'Unused investment credit from the electricity credit from cooperatives', 'Unused investment credit from the energy credit from cooperatives', 'Unused investment credit from rehabilitation credit from cooperatives', 'Advanced manufacturing production credit', 'Clean electricity production credit', 'Clean fuel production credit', 'Clean hydrogen production credit', 'Orphan drug credit', 'Enhanced oil recovery credit', 'Renewable electricity production credit', 'Biodiesel, renewable diesel, or sustainable aviation fuels credit', 'New markets credit', 'Credit for small employer pension plan startup costs', 'Credit for small employer auto-enrollment', 'Credit for small employer military spouse retirement plan', 'Credit for employer-provided childcare facilities and services', 'Low sulfur diesel fuel production credit', 'Qualified railroad track maintenance credit', 'Credit for oil and gas production from marginal wells', 'Distilled spirits credit', 'Energy efficient home credit', 'Reserved for future use', 'Alternative fuel vehicle refueling property credit', 'Clean renewable energy bond credit', 'New clean renewable energy bond credit', 'Qualified energy conservation bond credit', 'Qualified zone academy bond credit', 'Qualified school construction bond credit', 'Build America bond credit', 'Credit for employer differential wage payments', 'Carbon oxide sequestration credit', 'Carbon oxide sequestration credit recapture', 'New clean vehicles credit', 'Qualified commercial clean vehicle credit', 'Credit for small employer health insurance premiums', 'Employer credit for paid family and medical leave', 'Transferred credits, section 6418', ...Array<string>(4).fill('Reserved for future use')],
  17: K1_CODE_REFERENCE_2019[17],
  18: K1_CODE_REFERENCE_2019[18],
  19: [...K1_CODE_REFERENCE_2019[19], 'Deemed distributions of money - decreases in partnership liabilities', 'Reserved for future use', 'For performing services - cash and marketable securities', 'For performing services - other property'],
  20: [...K1_CODE_REFERENCE_2019[20].slice(0, 5), 'Recapture of low-income housing credit for section 42(j)(5) partnerships', 'Recapture of low-income housing credit for other partnerships', ...K1_CODE_REFERENCE_2019[20].slice(7, 13), 'Business interest expense (information item)', 'Section 453(l)(3) information', 'Section 453A(c) information', 'Section 1260(b) information', 'Interest allocable to production expenditures', 'Capital construction fund (CCF) nonqualified withdrawals', 'Depletion deduction', 'Section 743(b) basis adjustment', 'Unrelated business taxable income', 'Precontribution gain (loss)', 'Payment obligations including guarantees and deficit obligations', 'Net investment income', 'Section 199A information', 'Section 704(c) information', 'Section 751 gain (loss)', 'Section 1(h)(5) collectibles gain', 'Section 1(h)(6) unrecaptured section 1250 gain', 'Excess taxable income', 'Excess business interest income', 'Gross receipts for section 448(c)', 'Noncash charitable contributions', 'Interest and tax on deferred compensation to partners', 'Excess business loss limitation', 'Gain from mark-to-market election', 'Section 721(c) partnership', 'Section 1061 information', 'Farming and fishing income', 'PTP information', 'Inversion gain', 'Conservation reserve program payments', 'IRA disclosure', 'Qualifying advanced coal project property and qualifying gasification project property', 'Qualifying advanced energy project property', 'Advanced manufacturing investment property', 'Clean electricity investment property', 'Reportable transactions', 'Corporate alternative minimum tax (CAMT)', 'Foreign partners, Form 8990, Schedule A', 'Reimbursement of preformation expenditures', ...Array<string>(4).fill('Reserved for future use')],
}

export const k1CodeDescription = (year: number | null, box: number, code: string): string | null => {
  if (!/^[A-Z]{1,2}$/.test(code)) return null
  const reference = year === 2019 ? K1_CODE_REFERENCE_2019 : year === 2025 ? K1_CODE_REFERENCE_2025 : null
  if (!reference) return null
  if (year === 2025 && code === 'ZZ') return ({ 11: 'Other income (loss)', 13: 'Other deductions', 15: 'Other credits', 20: 'Other information' } as Record<number, string>)[box] ?? null
  const index = [...code].reduce((value, letter) => value * 26 + letter.charCodeAt(0) - 64, 0) - 1
  return reference[box]?.[index] ?? null
}

export const K1_STATEMENT_BOXES = [11, 13, 14, 15, 16, 17, 18, 19, 20, 21] as const
