// Snapshot of the 500 largest common/ordinary-share symbols by market cap from
// the Nasdaq stock screener on 2026-09-25. This is deliberately vendored so CSV
// review remains deterministic and never depends on a live market-data call.
const TOP_500_EQUITY_SYMBOLS = `
NVDA AAPL GOOGL GOOG MSFT AMZN SPCX META AVGO TSLA MU LLY AMD JPM WMT INTC XOM JNJ MA ABBV PLTR ORCL CSCO CVX COST BAC LRCX KO AMAT CAT MRK HSBC DELL PG UNH GE PANW MS NFLX PM HD RY NVS GS MUFG CRWD SHEL ANET SNDK AZN GEV RTX TMO WFC TXN KLAC TM MRVL C AMGN BHP LIN IBM STX AXP APH QCOM TTE VZ CRM TD DE GILD ADI DIS TMUS PEP ABT SCHW NVO ETN WELL SCCO MCD BLK UNP BBVA WDC PFE NEE DHR BA COP UBS TJX NOW UBER ISRG GLW VRTX FTNT CB NET PLD BMY PH BTI LMT COF BMO SPGI RIO ACN BKNG SNOW PGR HDB BP MDT BNS VLO MPC CVS HOOD SBUX LOW SPOT ING APP ADP FCX SYK ENB EQIX PSX BNY MCK CM GSK IBN CNQ AEM ASX CME RACE SO PWR VRT ADBE CEG DDOG HCA MAR HWM USB GD ABNB PNC MELI CDNS DUK ICE BX EMR CSX E MMM ELV WMB KKR HPE LITE WM BCS REGN SNPS DASH MRSH MCO EPD SU CTAS BE CMCSA UPS AMT CP SHW MRNA MDLZ ITW WBD ECL SLB TRV MSI ROST EOG INTU MFC CNI NOC NWG CMI APO TGT GM CVNA NSC HLT CI ORLY B KMI CL HON DB DLR SPG NBIS FDX NU MPWR WPM RSG BSX AEP RCL URI APD ALAB MSTR TEL MET TDG KEYS TRGP UMC TER GWW IMO TRP COR NTRA TAK CVE AON PCAR AJG FAST NXPI OXY FIX TFC OKE ALL AFL LNG COHR GRMN BKR NUE CRH DAL DVN NKE D CTVA FANG NDAQ COIN O CAH SRE CIEN HONA PSA AU STT CRWV EW F CBRS WAB BDX TEAM A DEO ROK VMRK EBAY TEVA AZO FITB VST RKLB XYZ STM WDAY TWLO ETR HUM MDLN CCEP IQV CARR PYPL VTR VEEV LHX SLF ADSK AMP TRI XEL CLS RVMD HEI FERG WAT KDP HMC FLEX EXC ILMN PRU IBKR P MCHP HLN CMG IDXX MSCI LYV FMX FER WCN ARES CBRE ADM DHI AIG NTAP SYY CCJ ED TTWO CRDO ODFL PAYX AXON BAP OKTA UAL ROP NTR VIK TKO ZS RBLX KR EL ESLT UI HIG IRM MDB KVUE RKT HSY RPRX BIIB ALNY PEG EME VG PCG DXCM WEC TECK JBL EQT ACGL KMB ALC QSR RMD NTRS PUK MTB VMC HBAN CNC RJF MTD GEHC EXPE CBOE CCL SUNB RDDT KGC ZTS IR MLM CCI ON TDY KHC HPQ EXR AEE HAL SMCI WTW CFG FTS DG WSM FOXA SYM SYF INSM ATO PBA NVT ZM VRSN WST CPAY ECHO GFS AWK DGX ROIV CPRT CTSH VICI Q OTIS ATI DOV FFIV INCY DTE LH LVS FE WRB CPNG SN CINF HUBB TSEM FISV PFG CNP AFRM SW FOX PPL ES XYL EXPD LPLA FWONK ASTS GH TW DRI PPG CRCL RBRK ULTA VLTO TPL FCNCA RF IOT ROKU ENTG CHD BSP GPN AER TPR TROW PHM RIVN CASY VRSK IFF MTSI FWONA SOFI KEY JBHT MKL L ARXS
`.trim().split(/\s+/)

// These statement symbols are listed common/ordinary shares in the same Nasdaq
// reference but fall below the top-500 market-cap cutoff.
const STATEMENT_EQUITY_SYMBOLS = ['KBDC', 'KLAR']

const knownEquitySymbols = new Set([...TOP_500_EQUITY_SYMBOLS, ...STATEMENT_EQUITY_SYMBOLS])

export const normalizeEquitySymbol = (value: unknown): string =>
  typeof value === 'string' ? value.trim().toUpperCase().replace('-', '.') : ''

export const isKnownEquitySymbol = (value: unknown): boolean =>
  knownEquitySymbols.has(normalizeEquitySymbol(value))
